[bumpver]
current_version = "1.0.33"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "Bump version {old_version} -> {new_version} [skip ci]"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = false
push = false

[bumpver.file_patterns]
"bumpver.toml" = [
    'current_version = "{version}"',
]

"testVer.txt" = [
    'version is {version}',
]
