name: build

on: [push]

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      # Waits until no release workflow is running
      - name: "Queue for release"
        uses: ahmadnassri/action-workflow-queue@v1

      # Create app key for admin access
      - name: "Create github app token"
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          # Create fork this action and create a private app
          # then use the ID and PRIVATE_KEY in this action
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          # Fetch full git history and tags
          fetch-depth: 0
          # Ensure that git uses your token with admin access to the repo
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false

      - name: Install bumpver
        run: pipx install bumpver

      - name: "Install auto"
        run: |
          curl -qkL -o - https://github.com/intuit/auto/releases/download/v11.2.1/auto-linux.gz | gunzip > ~/auto
          chmod a+x ~/auto

      - name: "Run auto shipit"
        env: # token as an environment variable
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: "~/auto shipit"
