name: build

on: [push]

jobs:
  release:
    permissions: write-all
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          # Ensure that git uses your token with admin access to the repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare repository
        # Fetch full git history and tags
        run: git fetch --unshallow --tags

      - name: "install auto"
        run: |
          curl -qkL -o - https://github.com/intuit/auto/releases/download/v10.28.0/auto-linux.gz | gunzip > ~/auto
          chmod a+x ~/auto
      - name: "auto shipit"
        env: # Or as an environment variable
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "~/auto shipit"
