name: build

on: [push]

jobs:
  release:
    permissions: write-all
    runs-on: "ubuntu-latest"
    steps:
      # Waits until no release workflow is running 
      - name: "Queue for release"
        uses: ahmadnassri/action-workflow-queue@v1

      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          # Fetch full git history and tags
          fetch-depth: 0
          # Ensure that git uses your token with admin access to the repo
          token: ${{ secrets.ADMIN_TOKEN }}

      - name: "Install auto"
        run: |
          curl -qkL -o - https://github.com/intuit/auto/releases/download/v10.28.0/auto-linux.gz | gunzip > ~/auto
          chmod a+x ~/auto

      - name: "Run auto shipit"
        env: # Or as an environment variable
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "~/auto shipit"
